# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Arch Linux's package builder"
description: "GitHub Action to build Arch Linux's package"
author: 'kamack38'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  path:
    description: 'Location for this action to run'
    default: ''
    required: false
  pkgver:
    description: 'Update pkgver on PKGBUILD'
    default: ''
    required: false
  pkgrel:
    description: 'Update pkgrel on PKGBUILD'
    default: ''
    required: false
  updpkgsums:
    description: 'Update checksums on PKGBUILD'
    default: 'false'
    required: false
  srcinfo:
    description: 'Generate new .SRCINFO'
    default: 'false'
    required: false
  flags:
    description: 'Extra flags for makepkg'
    default: '-cfs --noconfirm'
    required: false
  namcap:
    description: 'Validate package with namcap'
    default: 'true'
    required: false
  paru:
    description: 'Make package using paru'
    default: 'false'
    required: false
  aur_pkgname:
    description: 'AUR package name'
    required: false
  aur_commit_username:
    description: 'The username to use when pushing package to the AUR'
    required: false
  aur_commit_email:
    description: 'The email to use when pushing package to the AUR'
    required: false
  aur_ssh_private_key:
    description: 'Your private key with access to the AUR package.'
    required: false
  aur_commit_message:
    description: 'Commit message to use when pushing package to the AUR'
    required: false
  aur_force_push:
    description: 'Use --force when pushing to the AUR.'
    required: false
    default: 'false'
outputs:
  OLD_PKGVER:
    description: 'Old package version'
  NEW_PKGVER:
    description: 'New package version'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.pkgver }}
    - ${{ inputs.pkgrel }}
    - ${{ inputs.updpkgsums }}
    - ${{ inputs.srcinfo }}
    - ${{ inputs.flags }}
    - ${{ inputs.namcap }}
    - ${{ inputs.paru }}
    - ${{ inputs.aur_pkgname }}
    - ${{ inputs.aur_commit_username }}
    - ${{ inputs.aur_commit_email }}
    - ${{ inputs.aur_commit_message }}
    - ${{ inputs.aur_ssh_private_key }}
    - ${{ inputs.aur_force_push }}
