# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Arch Linux's package action"
description: "GitHub Action to run Arch Linux's package tools"
author: "datakrama"
branding:
  icon: "package"
  color: "green"

inputs:
  path:
    description: "Location for this action to run"
    default: $INPUT_GITHUB_WORKSPACE
    required: false
  updpkgsums:
    description: "Update checksums on PKGBUILD"
    default: "false"
    required: false
  srcinfo:
    description: "Generate new .SRCINFO"
    default: "false"
    required: false
  flags:
    description: "Extra flags for makepkg"
    default: "-cfs --noconfirm"
    required: false
  namcap:
    description: "Validate package with namcap"
    default: "true"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.updpkgsums }}
    - ${{ inputs.flags }}
    - ${{ inputs.namcap }}
