name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "main"

jobs:
  pretest:
    name: Test (with Dockerfile)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml

      - name: Get sample PKGBUILD
        run: wget https://github.com/datakrama/plenti-bin/raw/f5ffaaee02a2119aa16f6b7a27e87e198e096b47/PKGBUILD

      - name: Running test
        uses: ./
        with:
          pkgver: '0.4.26'
          pkgrel: 2
          updpkgsums: true
          srcinfo: true

      - name: Show diff
        run: |
          ls -la
          git diff PKGBUILD
          git diff .SRCINFO

  publish:
    name: Publish container image
    needs: pretest
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: OCI meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=main
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    name: Test (with prebuilt Container Image)
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get sample PKGBUILD
        run: wget https://github.com/datakrama/plenti-bin/raw/f5ffaaee02a2119aa16f6b7a27e87e198e096b47/PKGBUILD

      - name: Update action.yml to use edge tagged container image
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i 's/.*image\:.*/  image\: \"docker\:\/\/ghcr.io\/${{ github.repository_owner }}\/${{ github.event.repository.name }}\:edge\"/' action.yml
          cat action.yml

      - name: Running test
        uses: ./
        with:
          pkgver: '0.4.26'
          pkgrel: 2
          updpkgsums: true
          srcinfo: true

      - name: Show diff
        run: |
          ls -la
          git diff PKGBUILD
          git diff .SRCINFO

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch/tag names
        id: branch-name
        uses: tj-actions/branch-names@v5
        with:
          strip_tag_prefix: "v"

      - name: Read changelog
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.branch-name.outputs.tag }}
          path: ./CHANGELOG.md

      - name: Create/update release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.branch-name.outputs.tag }}
          name: v${{ steps.branch-name.outputs.tag }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
